baseURL = "https://test.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "Matěj Hejda"
theme = "KeepIt"
preserveTaxonomyNames = true
pygmentsUseClasses = true
pygmentsCodefences = true

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
disqusShortname = "yourdiscussshortname"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xHTML = false

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "categories"
    url = "/categories/"
    weight = 2
    
  [[menu.main]]
    name = "notes"
    url = "/notes"
    weight = 3

  [[menu.main]]
    name = "about"
    url = "/about"
    weight = 4

[params]
    since = 2020
    author = "Matěj Hejda"               # Author's name
    subtitle_main = "Matěj Hejda"
    subtitle_minor1 = "doctoral candidate at University of Strathclyde, Glasgow | nanoscale photonics for neuromorphics systems"
    subtitle_minor2 = "science | tech & AI | travelling | photography | electronic music "
    description = "Made in Czechia, living in Scotland"
    socialShare = true
    cdn_url = ""           # Base CDN URL
    #home_mode = "other" # post or other
    #avatar = "/images/me/avatar.jpg" #comment it to use gravatar
    keywords = "keyword1, keyword2" # site keywords


    google_verification = ""
    bing_verification = ""
    yandex_verification = ""
    pinterest_verification = ""
    baidu_verification = ""



    license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.gravatar]
    email = "hejdis@gmail.com"   #uncomment and insert your email address to use gravatar

[params.social]
    Facebook = "thisismatej"
    Twitter = "thisismatej"
    #GitHub = "xxxx"
    Linkedin = "matejhejda"
    
    Instagram = "thisismatej"
    #Email   = "xxxx"
    
    Telegram = "matej_h"
    Keybase = "thisismatej"
    Soundcloud = "noyire"
    #Spotify = "xxxx"
    Bandcamp = "noyire"
    Goodreads = "thisismatej"
    
    Googlescholar = "UpnbK3UAAAAJ"
    #Researchgate = "xxxx"
           
    #Youtubelegacy = "xxxx"
    #Youtubecustom = "xxxx"
    #Youtubechannel = "xxxx"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Medium = "xxxx"
    #Gitlab = "xxxx"    
    #Pinterest = "xxxx"
    #Reddit = "xxxx"
    #Codepen = "xxxx"
    #Bitbucket = "xxxx"
    #Stackoverflow = "xxxxx"
    #Weibo = "xxxx"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"

    #Paypal = "xxxx"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"

    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "xxxx"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    #Steam = "xxxx"
    #Twitch = "xxxx"
    #Strava = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    #Zhihu = "xxxx"
    #Douban = "xxxx"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"

    #Mastodon = "xxxx"
    #Thingiverse = "xxxx"

[params.share]
Facebook = true
Twitter = true
Linkedin = true
Googlescholar = true
Researchgate  = true
Goodreads = true
Bandcamp = true
Soundcloud = true
Keybase = true
Telegram = true
Instagram = true

# Used only for Seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "Matěj Hejda"

  [params.publisher]
    name = "Matěj Hejda"

    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  [params.image]
    url = "cover.png"
    width = 800
    height = 600

[params.gitalk]
owner = ""       # Your GitHub ID
repo = ""        # The repo to store comments
clientId = ""    # Your client ID
clientSecret = "" # Your client secret

[params.valine]
  enable = false
  language = 'en'
  appId = 'your appId'
  appKey = 'your appKey'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm'
  placeholder = 'your comments ...'
  visitor = true

[params.utterances]       # https://utteranc.es/
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments

[params.gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret
