---
label: Default
hide_body: true
display_field: title
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: list
  name: type
  label: type
  hidden: true
  config:
    use_select: false
- type: list
  name: tags
  label: tags
- type: datetime
  name: date
  label: date
- type: list
  name: categories
  label: categories
- type: list
  name: series
  label: series
- type: field_group
  name: author
  label: author
  fields:
  - type: text
    name: name
    label: name
- name: slug
  type: text
  config:
    required: false
  label: Slug
  description: 'URL ending:'
pages:
- content/posts/munro-4-beinn-chabhair.md
