---
label: Default
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: list
  name: type
  label: type
- type: list
  name: tags
  label: tags
- type: datetime
  name: date
  label: date
- type: list
  name: categories
  label: categories
- type: list
  name: series
  label: series
- type: field_group
  name: author
  label: author
  fields:
  - type: text
    name: name
    label: name
pages:
- content/posts/munro-4-beinn-chabhair.md
